# Generated by Django 3.2.12 on 2022-03-23 13:03

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pics_artist',
            field=models.ImageField(blank=True, upload_to='picsArtist'),
        ),
        migrations.AddField(
            model_name='groups',
            name='pics_group',
            field=models.ImageField(blank=True, upload_to='picsArtist'),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar_user',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='events',
            name='av_ticket',
            field=models.IntegerField(null=True, verbose_name=django.forms.widgets.NumberInput),
        ),
        migrations.AlterField(
            model_name='events',
            name='group',
            field=models.ManyToManyField(blank=True, to='event.Groups'),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.ManyToManyField(blank=True, to='event.Users'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hallcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='hall_category',
            field=models.ManyToManyField(blank=True, to='event.HallCategory'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='size_hall',
            field=models.IntegerField(null=True, verbose_name=django.forms.widgets.NumberInput),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
