# Generated by Django 3.2.12 on 2022-03-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220323_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='begin_date',
            field=models.DateTimeField(verbose_name="Date de dÃ©but d'event"),
        ),
    ]
